"""
ゲーム設定
==========
画像の間取りに基づくレイアウト:
  左上: 食洗器 / 左下: 洗い上がりゾーン / 右: パズル(皿セット)ゾーン
"""

# === 画面 ===
SCREEN_WIDTH = 480
SCREEN_HEIGHT = 360
TITLE = "Dish-Washing x Puzzle"
FPS = 30

# === タイマー ===
GAME_TIME_SECONDS = 120
TIMER_WARNING_SEC = 10

# === パズル ===
GRID_SIZE = 5
CELL_SIZE = 28
STOCK_PIECE_COUNT = 5
STOCK_MINI_CELL = 7
STOCK_SLOT_SIZE = 44
COMPLETE_ANIM_SEC = 1.0

# パズルパネル (オーバーレイ)
PUZZLE_PANEL_W = 420
PUZZLE_PANEL_H = 330
PUZZLE_PANEL_X = (SCREEN_WIDTH - PUZZLE_PANEL_W) // 2
PUZZLE_PANEL_Y = (SCREEN_HEIGHT - PUZZLE_PANEL_H) // 2
PUZZLE_BOARD_PIXEL = GRID_SIZE * CELL_SIZE
PUZZLE_BOARD_X = PUZZLE_PANEL_X + (PUZZLE_PANEL_W - PUZZLE_BOARD_PIXEL) // 2
PUZZLE_BOARD_Y = PUZZLE_PANEL_Y + 36
PUZZLE_STOCK_Y = PUZZLE_BOARD_Y + PUZZLE_BOARD_PIXEL + 20

# === スコア ===
SCORE_PER_CELL = 10
SCORE_COMPLETE_BONUS = 100
SCORE_PER_SORT = 5       # 皿1枚仕分け

# === 洗浄機 ===
WASHER_TIME_SECONDS = 8

# === 洗い上がり仕分け ===
SORT_DISH_COUNT = 8       # 1バッチあたりの皿数
CLEAN_PANEL_W = 420
CLEAN_PANEL_H = 330
CLEAN_PANEL_X = (SCREEN_WIDTH - CLEAN_PANEL_W) // 2
CLEAN_PANEL_Y = (SCREEN_HEIGHT - CLEAN_PANEL_H) // 2

# === 洗い場レイアウト (間取り図ベース) ===
#  左列: 食洗器(上) / 洗い上がり(下)
#  右側: パズルゾーン(大)
ZONE_LEFT_W = 152
ZONE_LEFT_X = 10
ZONE_RIGHT_X = ZONE_LEFT_X + ZONE_LEFT_W + 10
ZONE_RIGHT_W = SCREEN_WIDTH - ZONE_RIGHT_X - 10
ZONE_Y = 30
ZONE_FULL_H = SCREEN_HEIGHT - ZONE_Y - 10

WASHER_ZONE_X = ZONE_LEFT_X
WASHER_ZONE_Y = ZONE_Y
WASHER_ZONE_W = ZONE_LEFT_W
WASHER_ZONE_H = ZONE_FULL_H // 2 - 4

CLEAN_ZONE_X = ZONE_LEFT_X
CLEAN_ZONE_Y = ZONE_Y + WASHER_ZONE_H + 8
CLEAN_ZONE_W = ZONE_LEFT_W
CLEAN_ZONE_H = ZONE_FULL_H - WASHER_ZONE_H - 8

PUZZLE_ZONE_X = ZONE_RIGHT_X
PUZZLE_ZONE_Y = ZONE_Y
PUZZLE_ZONE_W = ZONE_RIGHT_W
PUZZLE_ZONE_H = ZONE_FULL_H

# === カラー ===
COL_BG = 0
COL_GRID_EMPTY = 1
COL_GRID_LINE = 5
COL_GRID_BORDER = 13
COL_TEXT = 7
COL_TEXT_ACCENT = 10
COL_STOCK_BG = 1
COL_SELECTED_BG = 5
COL_SELECTED_BORDER = 10
COL_COMPLETE_FLASH = 10
COL_TIMER_NORMAL = 7
COL_TIMER_WARNING = 8
COL_ZONE_PUZZLE = 1
COL_ZONE_WASHER = 5
COL_ZONE_CLEAN = 3
COL_ZONE_BORDER = 13
COL_ZONE_HIGHLIGHT = 10
COL_PANEL_BG = 0
COL_PANEL_BORDER = 13

CUSTOM_COL_PREVIEW_OK = 16
CUSTOM_COL_PREVIEW_NG = 17
CUSTOM_COL_PREVIEW_OK_RGB = 0x2B6B3B
CUSTOM_COL_PREVIEW_NG_RGB = 0x6B2B3B
